/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import bowlingshoe.Sapato;
import bowlingshoe.SapatoDAO;
import java.awt.event.ItemEvent;
import javafx.event.EventType;
import javafx.scene.control.CheckBoxTreeItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Herson
 */
public class CdSapato extends javax.swing.JDialog {
    
    final CheckBoxTreeItem a = new CheckBoxTreeItem();
    
    
    public void itemStateChanged(ItemEvent e) {
        
    }
    
    public CdSapato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeItem = new javax.swing.JLabel();
        nItem = new javax.swing.JTextField();
        numeroItem = new javax.swing.JLabel();
        numItem = new javax.swing.JFormattedTextField();
        statusItem = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        infos = new javax.swing.JLabel();
        checkDisponivel = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Itens");
        setResizable(false);

        nomeItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeItem.setText("Descrição do Item:* ");

        nItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nItemActionPerformed(evt);
            }
        });

        numeroItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroItem.setText("Tamanho:*");

        numItem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        numItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numItemActionPerformed(evt);
            }
        });

        statusItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusItem.setText("Status:");

        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btIncluir.setText("INCLUIR ITEM");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        infos.setText("*Informações obrigatórias");

        checkDisponivel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkDisponivel.setSelected(true);
        checkDisponivel.setText("Disponível");
        checkDisponivel.setEnabled(false);
        checkDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDisponivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomeItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(447, 447, 447))
                    .addComponent(numeroItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numItem)
                        .addGap(488, 488, 488))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nItem)
                        .addGap(237, 237, 237))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97)
                        .addComponent(btIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDisponivel)
                            .addComponent(infos)
                            .addComponent(statusItem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(nomeItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nItem)
                .addGap(27, 27, 27)
                .addComponent(numeroItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numItem)
                .addGap(34, 34, 34)
                .addComponent(statusItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkDisponivel)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(infos)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        int id = 0;
        String nome = nItem.getText();
        String tamanho = numItem.getText();
        if (tamanho.equals("")) {
            tamanho = "0";
        }
        int tam = Integer.parseInt(tamanho);

        if (nome.equals("") || tam == 0) {
            JOptionPane.showMessageDialog(null, "Dados incorretos ou campos inválidos.\n Digite novamente por favor!");
        } else {
            Sapato sapato = new Sapato(id, nome, tam, "D");
            SapatoDAO dao = new SapatoDAO();
            dao.inserirSapato(sapato);
            this.setVisible(false);
            
        }


    }//GEN-LAST:event_btIncluirActionPerformed

    private void nItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nItemActionPerformed

    private void numItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numItemActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        Object[] opcao = {"SIM", "NÃO"};

        int n = JOptionPane.showOptionDialog(this, "Tem certeza que "
                + "deseja cancelar a operação? ", "Selecione uma opção!", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opcao, opcao[1]);
        if (n == 0) {
            CdSapato.this.setVisible(false);
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void checkDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDisponivelActionPerformed
        
    }//GEN-LAST:event_checkDisponivelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JCheckBox checkDisponivel;
    private javax.swing.JLabel infos;
    private javax.swing.JTextField nItem;
    private javax.swing.JLabel nomeItem;
    private javax.swing.JFormattedTextField numItem;
    private javax.swing.JLabel numeroItem;
    private javax.swing.JLabel statusItem;
    // End of variables declaration//GEN-END:variables
}
