/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bowlingshoe;

import javax.swing.JOptionPane;

/**
 *
 * @author marcos.vpvsantos
 */
public class TelaRetirada extends javax.swing.JFrame {

    /**
     * Creates new form telaAluga
     */
    public TelaRetirada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ncliente = new javax.swing.JLabel();
        dadoCliente = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        btConfirmar = new javax.swing.JButton();
        btCancelar = new javax.swing.JToggleButton();
        cpfCliente = new javax.swing.JFormattedTextField();
        Infos = new javax.swing.JLabel();
        Funcionario = new javax.swing.JLabel();
        IDFuncionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        ncliente.setText("Nome do Cliente*");

        dadoCliente.setText("CPF*");

        nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteActionPerformed(evt);
            }
        });

        btConfirmar.setText("AVANÇAR");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        try {
            cpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfClienteActionPerformed(evt);
            }
        });

        Infos.setText("*Informações obrigatórias");

        Funcionario.setText("ID Funcionário*");

        IDFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ncliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(230, 230, 230))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41)
                                .addComponent(btConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Infos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(188, 188, 188)))
                        .addGap(183, 183, 183))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dadoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(95, 95, 95))
                                    .addComponent(cpfCliente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(IDFuncionario)
                                        .addGap(70, 70, 70)))
                                .addGap(377, 377, 377)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ncliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dadoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfCliente)
                .addGap(18, 18, 18)
                .addComponent(Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDFuncionario)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Infos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        TelaRetirada.this.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        String nome = nomeCliente.getText();
        String cpf = cpfCliente.getText();
        String idFuncionario = IDFuncionario.getText();
        
        if (nome.equals("") || cpf.trim().equals("") || idFuncionario.equals("")) {
            JOptionPane.showMessageDialog(null, "Dados incorretos ou campos inválidos.\n Digite novamente por favor!");
        } else {

            int digitosCPF = cpf.length();
            int someCPF, divisaoCPF, segundaSomaCPF, segundaDivisaoCPF;
            int a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11;
            int b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11;
            int c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11;

            if (digitosCPF == 14) {
                a1 = Character.getNumericValue(cpf.charAt(0));
                a2 = Character.getNumericValue(cpf.charAt(1));
                a3 = Character.getNumericValue(cpf.charAt(2));
                a4 = Character.getNumericValue(cpf.charAt(4));
                a5 = Character.getNumericValue(cpf.charAt(5));
                a6 = Character.getNumericValue(cpf.charAt(6));
                a7 = Character.getNumericValue(cpf.charAt(8));
                a8 = Character.getNumericValue(cpf.charAt(9));
                a9 = Character.getNumericValue(cpf.charAt(10));
                a10 = Character.getNumericValue(cpf.charAt(12));
                a11 = Character.getNumericValue(cpf.charAt(13));

                b1 = a1 * 1;
                b2 = a2 * 2;
                b3 = a3 * 3;
                b4 = a4 * 4;
                b5 = a5 * 5;
                b6 = a6 * 6;
                b7 = a7 * 7;
                b8 = a8 * 8;
                b9 = a9 * 9;

                someCPF = b1 + b2 + b3 + b4 + b5 + b6 + b7 + b8 + b9;
                divisaoCPF = someCPF % 11;
                if (divisaoCPF == 10) {
                    divisaoCPF = 0;
                }

                c1 = a1 * 9;
                c2 = a2 * 8;
                c3 = a3 * 7;
                c4 = a4 * 6;
                c5 = a5 * 5;
                c6 = a6 * 4;
                c7 = a7 * 3;
                c8 = a8 * 2;
                c9 = a9 * 1;

                segundaSomaCPF = c1 + c2 + c3 + c4 + c5 + c6 + c7 + c8 + c9;
                segundaDivisaoCPF = segundaSomaCPF % 11;
                if (segundaDivisaoCPF == 10) {
                    segundaDivisaoCPF = 0;
                }

                if (divisaoCPF == a10 && segundaDivisaoCPF == a11) {
                    ItensRetirar tela = new ItensRetirar();
                    tela.show();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Dados incorretos ou campos inválidos (CPF*).\n Digite novamente por favor!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Dados incorretos ou campos inválidos (CPF*).\n Digite novamente por favor!");
            }
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void cpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfClienteActionPerformed

    private void IDFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFuncionarioActionPerformed
        
    }//GEN-LAST:event_IDFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Funcionario;
    private javax.swing.JTextField IDFuncionario;
    private javax.swing.JLabel Infos;
    private javax.swing.JToggleButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JFormattedTextField cpfCliente;
    private javax.swing.JLabel dadoCliente;
    private javax.swing.JLabel ncliente;
    private javax.swing.JTextField nomeCliente;
    // End of variables declaration//GEN-END:variables
}
